### ISSUE TITLE
if Facebook is visited logged out, two sessions are created

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#29]
logged out => session
login (in the same window) => another session

should be only one with logged-in status

**Comment by HilKai** [comment]
this looks to be a serverside issue if im not mistaken,
I dont check the facebook logged in status at all:
https://github.com/HilKai/FBForschung/blob/083b40df6b7eccb6c3c6d7c40df23969dc8a123d/src/scripts/background.js#L292-L302

as you can see a new session gets created only if the last session was over an hour ago, otherwise the last sessionID gets used.

I do however save the last session ID provided by posting a https://fbforschung.de/posts
as seen here:
https://github.com/HilKai/FBForschung/blob/083b40df6b7eccb6c3c6d7c40df23969dc8a123d/src/scripts/background.js#L471-L477

so maybe the returned session id serverside is wrong?

**Comment by MarHai** [comment]
I rechecked the server and, essentially, this should work fine. It could, however, be a problem with the sent data. What do you send as full request with and without logged in users? Can you send me two exemplary Postman requests?

Also, as we have discussed some time ago, the one-hour lag should not be there. It should not exist at all. A session is defined by one opened Facebook window until the time it is either closed or reloaded. Otherwise, the ordinal numbering from posts (top to bottom) is messed up.

**Comment by HilKai** [comment]
fixed and testet this, if you log into facebook you get a new session, if you log out and back in, another session gets created
