### ISSUE TITLE
Firefox - remembers login-ID even when plugin is deleted and reinstalled

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#34]
can't create new account, all posts logged in one
 - can't test the plugin like this

**Comment by HilKai** [comment]
did you get to a registration form at all? currently on my side even this isnt working. The problem seems to be that firefox throws this error:

Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

**Comment by pheliaweiss** [comment]
after the first time installing I could register as usual, after this the plugin remembered me.
I got the same error - also I can only install the plugin temporarily for as long as I don't close the browser, is there an other way to do this?

**Comment by HilKai** [comment]
okay I fixed the registration however this is a really annoying bug? feature? in firefox

if you delete/remove the plugin nothing actually gets deleted (in the storage)
you can manually delete the storage by going to debug addons, then click debug on the addon and then go to console and type "_storage2.default.clear()" however you first need a breakpoint in the background script (go to the sources tab and click on any line so that a blue arrow apears, then reload the plugin). If all goes well this should delete the storage and the registration window should open.

Im not asking you to do it this way since honestly its really annyoing im trying to find  a better way at the moment. Its actually really hard though since for me the debug window wont even open anymore.. firefox seems to have some issues

**Comment by HilKai** [comment]
on installing the plugin all storage gets deleted now - this should resolve any firefox related issues
