### ISSUE TITLE
Firefox - does not open registration-site after installation of the plugin

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#45]
Win10: after installing the plugin a pop-up comes up in the adress bar 'FBForschung.de Browser-Plugin wurde zu Firefox hinzugefügt. ...'. Usually this minimizes to a symbol in the adress bar and the new tab for registration is opened. But sometimes (maybe if the connection is too slow?) it doesn't and the new site doesn't open.

**Comment by HilKai** [comment]
I feel like a lot of these issues are related to debuggin in firefox only, currently each time the browser gets started the plugin checks if a useridentification is given and if not it will open the install page. since firefox doesnt keep addons that are in development between session this doesnt work. Id rather wait for an alpha release to test these issues
Reinstalling the plugin / reloading should work for debugg pourposes 
paging @MarHai

**Comment by MarHai** [comment]
The plugin currently is in alpha release; we are using a legit and signed .xpi file. This is not related to dev. issues but a bug.

**Comment by HilKai** [comment]
ok this issue is again related to firefox, if you remove the addon the storage still doesnt get cleared, any help is apreciated as 

`function handleInstalled(details) {
  storage.clear();
  console.log("cleared Storage");
}
ext.runtime.onInstalled.addListener(handleInstalled);`

doesnt produce the wanted effect of clearing the sorage each time the plugin gets installed

**Comment by MarHai** [comment]
According to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled you need to attach the listener to the browser runtime (not the ext runtime).

**Comment by HilKai** [comment]
when using the current code it works while debuggin the extension, only the signed version doesn't work, current code gets executed on install

**Comment by HilKai** [comment]
@MarHai would It be possible to just include a *reset account* button on the options page- i really have no clue  how to fix this issue

**Comment by MarHai** [comment]
That would be fine for me. Go ahead and implement it 😊 thanks
________________________________
Von: HilKai <notifications@github.com>
Gesendet: Mittwoch, 25. April 2018 19:22
An: HilKai/FBForschung
Cc: Mario Haim; Mention
Betreff: Re: [HilKai/FBForschung] Firefox - does not open registration-site after installation of the plugin (#45) 

@MarHai would It be possible to just include a reset account button on the options page- i really have no clue how to fix this issue

**Comment by HilKai** [comment]
implemented button and confirmed working for chrome, firefox (debug), firefo(xpi file)
